version: '3.9'

services:
  options-app:
    container_name: options-app
    image: boomdoink/go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=options_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - options_db
  options_db:
    container_name: options_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
